# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ITB\Sem 5\RPL\coba\cart.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cart(object):
    def setupUi(self, Cart):
        Cart.setObjectName("Cart")
        Cart.resize(1280, 720)
        self.tableWidget = QtWidgets.QTableWidget(Cart)
        self.tableWidget.setGeometry(QtCore.QRect(20, 120, 1231, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.labelHarga = QtWidgets.QLabel(Cart)
        self.labelHarga.setGeometry(QtCore.QRect(320, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHarga.setFont(font)
        self.labelHarga.setText("")
        self.labelHarga.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHarga.setObjectName("labelHarga")
        self.labelNama = QtWidgets.QLabel(Cart)
        self.labelNama.setGeometry(QtCore.QRect(20, 30, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNama.setFont(font)
        self.labelNama.setText("")
        self.labelNama.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNama.setObjectName("labelNama")
        self.labelTotal = QtWidgets.QLabel(Cart)
        self.labelTotal.setGeometry(QtCore.QRect(530, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTotal.setFont(font)
        self.labelTotal.setText("")
        self.labelTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTotal.setObjectName("labelTotal")
        self.kuantitasText = QtWidgets.QLineEdit(Cart)
        self.kuantitasText.setGeometry(QtCore.QRect(900, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kuantitasText.setFont(font)
        self.kuantitasText.setText("")
        self.kuantitasText.setObjectName("kuantitasText")
        self.minButton = QtWidgets.QPushButton(Cart)
        self.minButton.setGeometry(QtCore.QRect(850, 40, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.minButton.setFont(font)
        self.minButton.setObjectName("minButton")
        self.plusButton = QtWidgets.QPushButton(Cart)
        self.plusButton.setGeometry(QtCore.QRect(990, 40, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")

        self.retranslateUi(Cart)
        QtCore.QMetaObject.connectSlotsByName(Cart)

    def retranslateUi(self, Cart):
        _translate = QtCore.QCoreApplication.translate
        Cart.setWindowTitle(_translate("Cart", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Cart", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Cart", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Cart", "Price"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Cart", "Total"))
        self.minButton.setText(_translate("Cart", "-"))
        self.plusButton.setText(_translate("Cart", "+"))
