# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ITB\Sem 5\RPL\Tubes\RPL_Kelompok8\src\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1281, 720)
        Dialog.setStyleSheet("QDialog#Dialog{\n"
"    background-color: #fff;\n"
"}")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 190, 1281, 531))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(250)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.labelHarga = QtWidgets.QLabel(Dialog)
        self.labelHarga.setGeometry(QtCore.QRect(530, 130, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelHarga.setFont(font)
        self.labelHarga.setStyleSheet("QLabel#labelHarga{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(225, 225, 225);\n"
"}")
        self.labelHarga.setFrameShape(QtWidgets.QFrame.Box)
        self.labelHarga.setText("")
        self.labelHarga.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHarga.setObjectName("labelHarga")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(720, 120, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.jumlahText = QtWidgets.QLineEdit(Dialog)
        self.jumlahText.setGeometry(QtCore.QRect(860, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.jumlahText.setFont(font)
        self.jumlahText.setStyleSheet("QLineEdit#jumlahText{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QLineEdit#jumlahText::focus{\n"
"    border: 2px solid blue;\n"
"}")
        self.jumlahText.setText("")
        self.jumlahText.setPlaceholderText("")
        self.jumlahText.setObjectName("jumlahText")
        self.addToCartButton = QtWidgets.QPushButton(Dialog)
        self.addToCartButton.setGeometry(QtCore.QRect(920, 130, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addToCartButton.setFont(font)
        self.addToCartButton.setStyleSheet("QPushButton#addToCartButton {\n"
"    background-color: #56BB86;\n"
"    border-radius: 10px;\n"
"    font:14px;\n"
"    color:#fff;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton#addToCartButton:hover {\n"
"    background-color:rgb(46, 209, 119);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"QPushButton#addToCartButton:pressed {\n"
"    background-color:rgb(58, 127, 90);\n"
"    border-style: inset;\n"
"}")
        self.addToCartButton.setObjectName("addToCartButton")
        self.labelNama = QtWidgets.QLabel(Dialog)
        self.labelNama.setGeometry(QtCore.QRect(90, 130, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNama.setFont(font)
        self.labelNama.setStyleSheet("QLabel#labelNama{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.labelNama.setFrameShape(QtWidgets.QFrame.Box)
        self.labelNama.setText("")
        self.labelNama.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNama.setObjectName("labelNama")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-1, 0, 1281, 71))
        self.frame.setStyleSheet("QFrame#frame {\n"
"    background-color: rgb(86, 187, 134);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gtCartButton = QtWidgets.QPushButton(self.frame)
        self.gtCartButton.setGeometry(QtCore.QRect(1140, 20, 112, 31))
        self.gtCartButton.setStyleSheet("QPushButton#gtCartButton {\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 10px;\n"
"    font:14px;\n"
"    color:#000;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton#gtCartButton:hover {\n"
"    background-color:rgb(231, 231, 231);\n"
"    border-style: inset;\n"
"}\n"
"QPushButton#gtCartButton:pressed {\n"
"    background-color:rgb(190, 190, 190);\n"
"    border-style: inset;\n"
"}")
        self.gtCartButton.setObjectName("gtCartButton")
        self.allMenuButton = QtWidgets.QPushButton(self.frame)
        self.allMenuButton.setGeometry(QtCore.QRect(820, 20, 112, 31))
        self.allMenuButton.setStyleSheet("QPushButton#allMenuButton {\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 10px;\n"
"    font:14px;\n"
"    color:#000;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton#allMenuButton:hover {\n"
"    background-color:rgb(231, 231, 231);\n"
"    border-style: inset;\n"
"}\n"
"QPushButton#allMenuButton:pressed {\n"
"    background-color:rgb(190, 190, 190);\n"
"    border-style: inset;\n"
"}")
        self.allMenuButton.setObjectName("allMenuButton")
        self.searchText = QtWidgets.QLineEdit(self.frame)
        self.searchText.setGeometry(QtCore.QRect(400, 20, 411, 31))
        self.searchText.setStyleSheet("QLineEdit#searchText{\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;\n"
"    padding:3px;\n"
"}\n"
"\n"
"QLineEdit#searchText::focus{\n"
"    border: 2px solid blue;\n"
"}\n"
"")
        self.searchText.setObjectName("searchText")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 100, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(530, 100, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame.raise_()
        self.tableWidget.raise_()
        self.labelHarga.raise_()
        self.label_3.raise_()
        self.jumlahText.raise_()
        self.addToCartButton.raise_()
        self.labelNama.raise_()
        self.label.raise_()
        self.label_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Gambar"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Harga"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Deskripsi"))
        self.label_3.setText(_translate("Dialog", "Jumlah : "))
        self.addToCartButton.setText(_translate("Dialog", "Add To Cart"))
        self.gtCartButton.setText(_translate("Dialog", "Go to cart"))
        self.allMenuButton.setText(_translate("Dialog", "All Menu"))
        self.searchText.setPlaceholderText(_translate("Dialog", "Search Here"))
        self.label.setText(_translate("Dialog", "Nama Makanan"))
        self.label_2.setText(_translate("Dialog", "Harga (Rp)"))
