# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ITB\Sem 5\RPL\coba\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 720)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 250, 1301, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.searchText = QtWidgets.QLineEdit(Dialog)
        self.searchText.setGeometry(QtCore.QRect(280, 10, 411, 31))
        self.searchText.setObjectName("searchText")
        self.searchButton = QtWidgets.QPushButton(Dialog)
        self.searchButton.setGeometry(QtCore.QRect(720, 10, 112, 34))
        self.searchButton.setObjectName("searchButton")
        self.allMenuButton = QtWidgets.QPushButton(Dialog)
        self.allMenuButton.setGeometry(QtCore.QRect(860, 10, 112, 34))
        self.allMenuButton.setObjectName("allMenuButton")
        self.labelHarga = QtWidgets.QLabel(Dialog)
        self.labelHarga.setGeometry(QtCore.QRect(490, 110, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelHarga.setFont(font)
        self.labelHarga.setText("")
        self.labelHarga.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHarga.setObjectName("labelHarga")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(700, 110, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.jumlahText = QtWidgets.QLineEdit(Dialog)
        self.jumlahText.setGeometry(QtCore.QRect(850, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.jumlahText.setFont(font)
        self.jumlahText.setText("")
        self.jumlahText.setObjectName("jumlahText")
        self.addToCartButton = QtWidgets.QPushButton(Dialog)
        self.addToCartButton.setGeometry(QtCore.QRect(1070, 120, 161, 34))
        self.addToCartButton.setObjectName("addToCartButton")
        self.gtCartButton = QtWidgets.QPushButton(Dialog)
        self.gtCartButton.setGeometry(QtCore.QRect(1100, 180, 112, 34))
        self.gtCartButton.setObjectName("gtCartButton")
        self.labelNama = QtWidgets.QLabel(Dialog)
        self.labelNama.setGeometry(QtCore.QRect(60, 110, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNama.setFont(font)
        self.labelNama.setText("")
        self.labelNama.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNama.setObjectName("labelNama")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("Dialog", "Gambar"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Harga"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Deskripsi"))
        self.searchButton.setText(_translate("Dialog", "Search"))
        self.allMenuButton.setText(_translate("Dialog", "All Menu"))
        self.label_3.setText(_translate("Dialog", "Jumlah : "))
        self.addToCartButton.setText(_translate("Dialog", "Add To Cart"))
        self.gtCartButton.setText(_translate("Dialog", "Go to cart"))
